import { RiskFlagDefinition } from "../types";

export const RISK_FLAG_CATALOG: Record<string, RiskFlagDefinition> = {
  cafe_da_manha_irregular: {
    flag: "cafe_da_manha_irregular",
    level: "warning",
    title: "Café da manhã irregular",
    description: "Vale atenção para começar o dia com mais regularidade alimentar.",
    relatedTopics: ["cafe_da_manha", "regularidade_refeicoes"],
  },
  baixa_frequencia_refeicoes: {
    flag: "baixa_frequencia_refeicoes",
    level: "warning",
    title: "Poucas refeições ao dia",
    description: "Longos intervalos sem comer podem prejudicar conforto e organização alimentar.",
    relatedTopics: ["regularidade_refeicoes", "planejamento_alimentar"],
  },
  baixo_consumo_leguminosas: {
    flag: "baixo_consumo_leguminosas",
    level: "warning",
    title: "Feijão e leguminosas em baixa frequência",
    description: "Há espaço para fortalecer esse grupo alimentar na rotina.",
    relatedTopics: ["feijao_e_leguminosas"],
  },
  baixo_consumo_frutas_verduras: {
    flag: "baixo_consumo_frutas_verduras",
    level: "warning",
    title: "Baixo consumo de frutas e verduras",
    description: "Esse ponto pode melhorar a qualidade geral da alimentação.",
    relatedTopics: ["frutas_e_verduras", "planejamento_alimentar"],
  },
  baixa_hidratacao: {
    flag: "baixa_hidratacao",
    level: "warning",
    title: "Hidratação insuficiente",
    description: "Vale organizar estratégias simples para aumentar o consumo de água.",
    relatedTopics: ["hidratacao", "saude_digestiva"],
  },
  alto_consumo_bebidas_acucaradas: {
    flag: "alto_consumo_bebidas_acucaradas",
    level: "warning",
    title: "Bebidas açucaradas frequentes",
    description: "Esse hábito merece atenção para reduzir exposição no dia a dia.",
    relatedTopics: ["bebidas_acucaradas", "hidratacao"],
  },
  alto_consumo_ultraprocessados: {
    flag: "alto_consumo_ultraprocessados",
    level: "warning",
    title: "Ultraprocessados frequentes",
    description: "Vale apoiar trocas possíveis e mais regulares.",
    relatedTopics: ["ultraprocessados", "planejamento_alimentar"],
  },
  refeicoes_com_tela: {
    flag: "refeicoes_com_tela",
    level: "warning",
    title: "Refeições com telas",
    description: "Comer com distrações pode atrapalhar atenção à fome e saciedade.",
    relatedTopics: ["rotina_sem_telas"],
  },
  baixa_atividade_fisica: {
    flag: "baixa_atividade_fisica",
    level: "warning",
    title: "Baixo nível de movimento",
    description: "Há oportunidade de incluir mais movimento compatível com a rotina.",
    relatedTopics: ["atividade_fisica", "sono"],
  },
  sono_irregular: {
    flag: "sono_irregular",
    level: "warning",
    title: "Sono irregular",
    description: "Descanso insuficiente pode impactar disposição e rotina alimentar.",
    relatedTopics: ["sono"],
  },
  seletividade_alimentar: {
    flag: "seletividade_alimentar",
    level: "warning",
    title: "Dificuldade com aceitação alimentar",
    description: "Esse ponto pede estratégias acolhedoras e progressivas.",
    relatedTopics: ["aceitacao_alimentar", "apoio_familiar"],
  },
  constipacao: {
    flag: "constipacao",
    level: "warning",
    title: "Queixa de prisão de ventre",
    description: "Vale observar água, fibras e frequência do desconforto.",
    relatedTopics: ["saude_digestiva", "hidratacao"],
  },
  perda_apetite: {
    flag: "perda_apetite",
    level: "warning",
    title: "Perda de apetite frequente",
    description: "Esse sinal merece observação e pode pedir avaliação se persistente.",
    relatedTopics: ["saude_digestiva", "acompanhamento_clinico"],
  },
  preocupacao_peso: {
    flag: "preocupacao_peso",
    level: "warning",
    title: "Preocupação com o peso",
    description: "Mudanças percebidas no peso pedem atenção acolhedora e orientação.",
    relatedTopics: ["acompanhamento_clinico", "imagem_corporal"],
  },
  imagem_corporal_em_risco: {
    flag: "imagem_corporal_em_risco",
    level: "warning",
    title: "Preocupação intensa com aparência",
    description: "Esse ponto merece escuta atenta e cuidado com a relação com a comida.",
    relatedTopics: ["imagem_corporal", "acompanhamento_clinico"],
  },
  dieta_restritiva: {
    flag: "dieta_restritiva",
    level: "warning",
    title: "Dieta restritiva sem apoio",
    description: "Restrições por conta própria podem trazer riscos e merecem orientação.",
    relatedTopics: ["imagem_corporal", "acompanhamento_clinico"],
  },
  sem_pre_natal: {
    flag: "sem_pre_natal",
    level: "high",
    title: "Pré-natal não realizado",
    description: "Esse ponto merece acompanhamento prioritário por profissional de saúde.",
    relatedTopics: ["pre_natal", "acompanhamento_clinico"],
  },
  dificuldade_mastigar: {
    flag: "dificuldade_mastigar",
    level: "high",
    title: "Dificuldade para mastigar",
    description: "Pode impactar ingestão alimentar e merece avaliação.",
    relatedTopics: ["mastigacao_e_degluticao", "acompanhamento_clinico"],
  },
  dificuldade_engolir: {
    flag: "dificuldade_engolir",
    level: "high",
    title: "Dificuldade para engolir",
    description: "Esse sinal merece atenção prioritária e avaliação oportuna.",
    relatedTopics: ["mastigacao_e_degluticao", "acompanhamento_clinico"],
  },
  perda_peso_involuntaria: {
    flag: "perda_peso_involuntaria",
    level: "high",
    title: "Perda de peso sem querer",
    description: "Mudança de peso involuntária merece acompanhamento mais próximo.",
    relatedTopics: ["acompanhamento_clinico", "mastigacao_e_degluticao"],
  },
  vulnerabilidade_social: {
    flag: "vulnerabilidade_social",
    level: "warning",
    title: "Barreiras sociais para se alimentar",
    description: "Custo, acesso ou apoio reduzido podem dificultar manter hábitos protetores.",
    relatedTopics: ["vulnerabilidade_social", "planejamento_alimentar"],
  },
  condicao_clinica_relevante: {
    flag: "condicao_clinica_relevante",
    level: "warning",
    title: "Condição clínica já conhecida",
    description: "Condições clínicas pedem atenção integrada com alimentação e acompanhamento.",
    relatedTopics: ["acompanhamento_clinico"],
  },
  longos_periodos_sem_comer: {
    flag: "longos_periodos_sem_comer",
    level: "warning",
    title: "Longos períodos sem comer",
    description: "Há espaço para ajustar a rotina e reduzir intervalos prolongados.",
    relatedTopics: ["regularidade_refeicoes", "planejamento_alimentar"],
  },
  baixo_apoio_familiar: {
    flag: "baixo_apoio_familiar",
    level: "warning",
    title: "Apoio familiar/social reduzido",
    description: "Rede de apoio reduzida pode dificultar a continuidade do cuidado alimentar.",
    relatedTopics: ["apoio_familiar", "vulnerabilidade_social"],
  },
  baixa_autonomia_protetora: {
    flag: "baixa_autonomia_protetora",
    level: "warning",
    title: "Autonomia alimentar com baixa proteção",
    description: "Vale fortalecer repertório para decisões alimentares mais seguras no cotidiano.",
    relatedTopics: ["autonomia_alimentar", "planejamento_alimentar"],
  },
};
