import { multiChoiceQuestion, option, singleChoiceQuestion, yesNoQuestion } from "../builders";
import { TriageQuestion } from "../../types";

export const fluxoAdolescente: TriageQuestion[] = [
  singleChoiceQuestion({
    id: "adolescente-autonomia",
    ageGroup: "adolescente",
    sectionId: "identificacao",
    title: "Quem costuma decidir mais sobre o que você vai comer ao longo do dia?",
    options: [
      option({ value: "eu", label: "Eu decido a maior parte", score: 0, flags: ["baixa_autonomia_protetora"], topics: ["autonomia_alimentar"] }),
      option({ value: "compartilhado", label: "Eu decido junto com a família", score: 1, topics: ["autonomia_alimentar", "apoio_familiar"] }),
      option({ value: "familia", label: "A família decide a maior parte", score: 0, topics: ["apoio_familiar"] }),
    ],
  }),
  yesNoQuestion({
    id: "adolescente-pula-cafe",
    ageGroup: "adolescente",
    sectionId: "rotina-alimentar",
    title: "Você costuma pular o café da manhã?",
    yes: {
      helperText: "Vale atenção: um café da manhã simples pode ajudar energia e concentração.",
      score: -1,
      flags: ["cafe_da_manha_irregular"],
      topics: ["cafe_da_manha", "planejamento_alimentar"],
    },
    no: {
      helperText: "Boa prática! Essa refeição ajuda a começar o dia com mais regularidade.",
      score: 1,
      topics: ["cafe_da_manha"],
    },
  }),
  singleChoiceQuestion({
    id: "adolescente-refeicoes-dia",
    ageGroup: "adolescente",
    sectionId: "rotina-alimentar",
    title: "Quantas refeições você costuma fazer por dia?",
    options: [
      option({ value: "2_ou_menos", label: "Até 2 refeições", score: -2, flags: ["baixa_frequencia_refeicoes"], topics: ["regularidade_refeicoes"] }),
      option({ value: "3", label: "3 refeições", score: 0, topics: ["regularidade_refeicoes"] }),
      option({ value: "4_5", label: "4 a 5 refeições", score: 1, topics: ["regularidade_refeicoes"] }),
      option({ value: "6_ou_mais", label: "6 ou mais", score: 0, topics: ["regularidade_refeicoes"] }),
    ],
  }),
  yesNoQuestion({
    id: "adolescente-substitui-refeicoes",
    ageGroup: "adolescente",
    sectionId: "rotina-alimentar",
    title: "Você costuma substituir refeições por lanches?",
    yes: {
      helperText: "Vale atenção: isso pode deixar a rotina mais irregular, principalmente em dias corridos.",
      score: -1,
      topics: ["regularidade_refeicoes", "planejamento_alimentar"],
    },
    no: {
      helperText: "Ótimo. Manter refeições principais ajuda bastante na organização do dia.",
      score: 1,
      topics: ["regularidade_refeicoes"],
    },
  }),
  yesNoQuestion({
    id: "adolescente-feijao",
    ageGroup: "adolescente",
    sectionId: "grupos-alimentares",
    title: "Você consome feijão ou outras leguminosas com regularidade?",
    yes: {
      helperText: "Boa prática! Esse grupo ajuda na saciedade e na qualidade da alimentação.",
      score: 1,
      topics: ["feijao_e_leguminosas"],
    },
    no: {
      helperText: "Vale buscar formas mais práticas de incluir feijão, lentilha ou grão-de-bico na semana.",
      score: -1,
      flags: ["baixo_consumo_leguminosas"],
      topics: ["feijao_e_leguminosas", "planejamento_alimentar"],
    },
  }),
  yesNoQuestion({
    id: "adolescente-frutas-verduras",
    ageGroup: "adolescente",
    sectionId: "grupos-alimentares",
    title: "Você consome frutas e verduras diariamente?",
    yes: {
      helperText: "Muito bem! Essa variedade protege a saúde e ajuda no intestino.",
      score: 1,
      topics: ["frutas_e_verduras"],
    },
    no: {
      helperText: "Vale atenção: pequenos ajustes e opções mais práticas podem ajudar bastante.",
      score: -1,
      flags: ["baixo_consumo_frutas_verduras"],
      topics: ["frutas_e_verduras", "planejamento_alimentar"],
    },
  }),
  multiChoiceQuestion({
    id: "adolescente-barreiras-frutas-verduras",
    ageGroup: "adolescente",
    sectionId: "grupos-alimentares",
    title: "O que mais dificulta esse consumo no dia a dia?",
    description: "Você pode marcar mais de uma opção.",
    visibleWhen: [{ questionId: "adolescente-frutas-verduras", operator: "equals", value: "nao" }],
    options: [
      option({ value: "escola", label: "Rotina da escola ou curso", topics: ["alimentacao_escolar_rotina"] }),
      option({ value: "praticidade", label: "Praticidade ou falta de tempo", topics: ["planejamento_alimentar"] }),
      option({ value: "gosto", label: "Não gosto muito", topics: ["aceitacao_alimentar", "autonomia_alimentar"] }),
      option({ value: "custo", label: "Custo ou acesso", flags: ["vulnerabilidade_social"], topics: ["vulnerabilidade_social"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adolescente-fast-food",
    ageGroup: "adolescente",
    sectionId: "grupos-alimentares",
    title: "Quantas vezes por semana você costuma consumir fast food?",
    type: "frequency",
    options: [
      option({ value: "nunca", label: "Quase nunca", score: 1, topics: ["ultraprocessados"] }),
      option({ value: "1_2", label: "1 a 2 vezes", score: 0, topics: ["ultraprocessados"] }),
      option({ value: "3_4", label: "3 a 4 vezes", score: -1, flags: ["alto_consumo_ultraprocessados"], topics: ["ultraprocessados", "planejamento_alimentar"] }),
      option({ value: "5_ou_mais", label: "5 vezes ou mais", score: -2, flags: ["alto_consumo_ultraprocessados"], topics: ["ultraprocessados", "planejamento_alimentar"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adolescente-refrigerante-energetico",
    ageGroup: "adolescente",
    sectionId: "grupos-alimentares",
    title: "Com que frequência você consome refrigerante ou energético?",
    type: "frequency",
    options: [
      option({ value: "raramente", label: "Raramente", score: 1, topics: ["bebidas_acucaradas"] }),
      option({ value: "1_2", label: "1 a 2 vezes por semana", score: 0, topics: ["bebidas_acucaradas"] }),
      option({ value: "3_4", label: "3 a 4 vezes por semana", score: -1, flags: ["alto_consumo_bebidas_acucaradas"], topics: ["bebidas_acucaradas", "hidratacao"] }),
      option({ value: "frequente", label: "Quase todos os dias", score: -2, flags: ["alto_consumo_bebidas_acucaradas"], topics: ["bebidas_acucaradas", "hidratacao"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adolescente-agua",
    ageGroup: "adolescente",
    sectionId: "hidratacao",
    title: "Você sente que bebe água em quantidade adequada?",
    options: [
      option({ value: "sim", label: "Sim, na maior parte dos dias", score: 1, topics: ["hidratacao"] }),
      option({ value: "parcial", label: "Às vezes", score: 0, topics: ["hidratacao"] }),
      option({ value: "nao", label: "Não", score: -1, flags: ["baixa_hidratacao"], topics: ["hidratacao", "alimentacao_escolar_rotina"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adolescente-imagem-corporal",
    ageGroup: "adolescente",
    sectionId: "sinais-alerta",
    title: "Existe preocupação excessiva com peso ou aparência?",
    options: [
      option({ value: "nao", label: "Não", score: 1, topics: ["imagem_corporal"] }),
      option({ value: "as_vezes", label: "Às vezes", score: -1, flags: ["imagem_corporal_em_risco"], topics: ["imagem_corporal"] }),
      option({ value: "frequente", label: "Com frequência", score: -2, flags: ["imagem_corporal_em_risco"], topics: ["imagem_corporal", "acompanhamento_clinico"] }),
    ],
  }),
  yesNoQuestion({
    id: "adolescente-dieta-restritiva",
    ageGroup: "adolescente",
    sectionId: "sinais-alerta",
    title: "Você já fez dieta restritiva por conta própria?",
    yes: {
      helperText: "Vale atenção: dietas muito restritivas sem apoio profissional podem fazer mal.",
      score: -2,
      flags: ["dieta_restritiva"],
      topics: ["imagem_corporal", "acompanhamento_clinico"],
    },
    no: {
      helperText: "Bom sinal. Buscar orientação antes de restringir alimentos é mais seguro.",
      score: 1,
      topics: ["imagem_corporal"],
    },
  }),
  yesNoQuestion({
    id: "adolescente-dieta-restritiva-acompanhada",
    ageGroup: "adolescente",
    sectionId: "sinais-alerta",
    title: "Houve orientação de profissional de saúde nessa dieta?",
    visibleWhen: [{ questionId: "adolescente-dieta-restritiva", operator: "equals", value: "sim" }],
    yes: {
      helperText: "Ótimo. Ter orientação ajuda a reduzir riscos e ajustar metas de forma segura.",
      score: 1,
      topics: ["acompanhamento_clinico"],
    },
    no: {
      helperText: "Esse ponto merece cuidado e conversa com a equipe de saúde.",
      score: -1,
      flags: ["dieta_restritiva"],
      topics: ["acompanhamento_clinico", "imagem_corporal"],
    },
  }),
  singleChoiceQuestion({
    id: "adolescente-compulsao",
    ageGroup: "adolescente",
    sectionId: "sinais-alerta",
    title: "Você percebe episódios de comer em excesso de forma difícil de controlar?",
    options: [
      option({ value: "nao", label: "Não", score: 1, topics: ["imagem_corporal"] }),
      option({ value: "as_vezes", label: "Às vezes", score: -1, topics: ["imagem_corporal", "acompanhamento_clinico"] }),
      option({ value: "frequente", label: "Com frequência", score: -2, flags: ["imagem_corporal_em_risco"], topics: ["imagem_corporal", "acompanhamento_clinico"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adolescente-apoio-refeicoes",
    ageGroup: "adolescente",
    sectionId: "contexto-familiar",
    title: "Você sente acompanhamento familiar nas refeições?",
    options: [
      option({ value: "frequente", label: "Na maioria dos dias", score: 1, topics: ["apoio_familiar"] }),
      option({ value: "as_vezes", label: "Às vezes", score: 0, topics: ["apoio_familiar"] }),
      option({ value: "raro", label: "Raramente", score: -1, flags: ["baixo_apoio_familiar"], topics: ["apoio_familiar", "vulnerabilidade_social"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adolescente-desafio",
    ageGroup: "adolescente",
    sectionId: "contexto-familiar",
    title: "Qual fator mais atrapalha cuidar melhor da alimentação hoje?",
    allowNotes: {
      label: "Se quiser, conte um pouco mais.",
      placeholder: "Ex.: horários, escola, gosto, rotina com amigos...",
      maxLength: 180,
    },
    options: [
      option({ value: "escola", label: "Rotina da escola ou curso", topics: ["alimentacao_escolar_rotina"] }),
      option({ value: "tempo", label: "Falta de tempo", topics: ["planejamento_alimentar"] }),
      option({ value: "gosto", label: "Prefiro lanches ou fast food", topics: ["autonomia_alimentar", "ultraprocessados"] }),
      option({ value: "custo", label: "Custo ou acesso", flags: ["vulnerabilidade_social"], topics: ["vulnerabilidade_social"] }),
      option({ value: "nenhum", label: "No momento está indo bem", score: 1, topics: ["apoio_familiar"] }),
    ],
  }),
  yesNoQuestion({
    id: "adolescente-refeicao-com-tela",
    ageGroup: "adolescente",
    sectionId: "habitos-diarios",
    title: "Você costuma comer enquanto usa celular ou computador?",
    yes: {
      helperText: "Vale atenção: comer distraído pode dificultar perceber fome e saciedade.",
      score: -1,
      flags: ["refeicoes_com_tela"],
      topics: ["rotina_sem_telas"],
    },
    no: {
      helperText: "Muito bem. Comer com mais atenção ajuda a organizar melhor as refeições.",
      score: 1,
      topics: ["rotina_sem_telas"],
    },
  }),
  singleChoiceQuestion({
    id: "adolescente-telas-horas",
    ageGroup: "adolescente",
    sectionId: "habitos-diarios",
    title: "Quantas horas por dia você passa em telas fora de estudo ou trabalho?",
    options: [
      option({ value: "ate_2h", label: "Até 2 horas", score: 1, topics: ["sono", "atividade_fisica"] }),
      option({ value: "3_5h", label: "3 a 5 horas", score: 0, topics: ["sono"] }),
      option({ value: "6_ou_mais", label: "6 horas ou mais", score: -1, flags: ["sono_irregular"], topics: ["sono", "atividade_fisica"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adolescente-atividade-fisica",
    ageGroup: "adolescente",
    sectionId: "habitos-diarios",
    title: "Como está sua rotina de atividade física?",
    options: [
      option({ value: "5_ou_mais", label: "5 dias ou mais por semana", score: 1, topics: ["atividade_fisica"] }),
      option({ value: "2_4", label: "2 a 4 dias por semana", score: 0, topics: ["atividade_fisica"] }),
      option({ value: "0_1", label: "0 a 1 dia por semana", score: -1, flags: ["baixa_atividade_fisica"], topics: ["atividade_fisica"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adolescente-sono",
    ageGroup: "adolescente",
    sectionId: "habitos-diarios",
    title: "Você sente que dorme bem?",
    options: [
      option({ value: "sim", label: "Sim", score: 1, topics: ["sono"] }),
      option({ value: "as_vezes", label: "Às vezes", score: 0, topics: ["sono"] }),
      option({ value: "nao", label: "Não", score: -1, flags: ["sono_irregular"], topics: ["sono"] }),
    ],
  }),
  yesNoQuestion({
    id: "adolescente-condicao-saude",
    ageGroup: "adolescente",
    sectionId: "condicoes-clinicas",
    title: "Você tem acompanhamento de saúde por alguma condição clínica?",
    yes: {
      helperText: "Ótimo. Isso ajuda a adaptar as orientações ao seu contexto.",
      score: 1,
      flags: ["condicao_clinica_relevante"],
      topics: ["acompanhamento_clinico"],
    },
    no: {
      helperText: "Tudo bem. Se surgir algum sinal de alerta, vale procurar a equipe de saúde.",
      score: 0,
      topics: ["acompanhamento_clinico"],
    },
  }),
  multiChoiceQuestion({
    id: "adolescente-condicoes-detalhe",
    ageGroup: "adolescente",
    sectionId: "condicoes-clinicas",
    title: "Se quiser, marque as condições que já conhece.",
    description: "Você pode marcar mais de uma opção.",
    visibleWhen: [{ questionId: "adolescente-condicao-saude", operator: "equals", value: "sim" }],
    options: [
      option({ value: "anemia", label: "Anemia", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "sobrepeso", label: "Sobrepeso ou obesidade", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "diabetes", label: "Diabetes", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "outra", label: "Outra condição", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
    ],
  }),
];
