import { multiChoiceQuestion, option, singleChoiceQuestion, yesNoQuestion } from "../builders";
import { TriageQuestion } from "../../types";

export const fluxoAdulto: TriageQuestion[] = [
  singleChoiceQuestion({
    id: "adulto-rotina-trabalho",
    ageGroup: "adulto",
    sectionId: "identificacao",
    title: "Como a sua rotina principal costuma funcionar?",
    options: [
      option({ value: "regular", label: "Horários mais regulares", score: 1, topics: ["planejamento_alimentar"] }),
      option({ value: "turnos", label: "Turnos, escala ou rotina variável", score: 0, topics: ["planejamento_alimentar"] }),
      option({ value: "cuidados_casa", label: "Cuidados da casa e da família", score: 0, topics: ["planejamento_alimentar", "apoio_familiar"] }),
      option({ value: "sem_rotina", label: "Sem rotina definida", score: -1, topics: ["planejamento_alimentar"] }),
    ],
  }),
  yesNoQuestion({
    id: "adulto-cafe-da-manha",
    ageGroup: "adulto",
    sectionId: "rotina-alimentar",
    title: "Você faz café da manhã com regularidade?",
    yes: {
      helperText: "Boa prática! Isso ajuda a começar o dia com mais organização alimentar.",
      score: 1,
      topics: ["cafe_da_manha"],
    },
    no: {
      helperText: "Vale atenção: um café da manhã simples pode fazer diferença em dias corridos.",
      score: -1,
      flags: ["cafe_da_manha_irregular"],
      topics: ["cafe_da_manha", "planejamento_alimentar"],
    },
  }),
  singleChoiceQuestion({
    id: "adulto-refeicoes-dia",
    ageGroup: "adulto",
    sectionId: "rotina-alimentar",
    title: "Quantas refeições você costuma fazer por dia?",
    options: [
      option({ value: "2_ou_menos", label: "Até 2 refeições", score: -2, flags: ["baixa_frequencia_refeicoes"], topics: ["regularidade_refeicoes"] }),
      option({ value: "3", label: "3 refeições", score: 0, topics: ["regularidade_refeicoes"] }),
      option({ value: "4_5", label: "4 a 5 refeições", score: 1, topics: ["regularidade_refeicoes"] }),
      option({ value: "6_ou_mais", label: "6 ou mais", score: 0, topics: ["regularidade_refeicoes"] }),
    ],
  }),
  yesNoQuestion({
    id: "adulto-almoco-regular",
    ageGroup: "adulto",
    sectionId: "rotina-alimentar",
    title: "Você costuma almoçar em horários regulares?",
    yes: {
      helperText: "Muito bem. Horários mais estáveis ajudam a organizar o restante do dia.",
      score: 1,
      topics: ["regularidade_refeicoes"],
    },
    no: {
      helperText: "Vale buscar um ponto de pausa possível, mesmo que simples, para reduzir correria.",
      score: -1,
      flags: ["longos_periodos_sem_comer"],
      topics: ["regularidade_refeicoes", "planejamento_alimentar"],
    },
  }),
  yesNoQuestion({
    id: "adulto-trabalho-pula-refeicao",
    ageGroup: "adulto",
    sectionId: "rotina-alimentar",
    title: "Seu trabalho ou rotina faz você pular refeições?",
    yes: {
      helperText: "Esse é um ponto comum na vida adulta. Pequenos apoios podem reduzir esses intervalos longos.",
      score: -1,
      flags: ["longos_periodos_sem_comer"],
      topics: ["regularidade_refeicoes", "planejamento_alimentar"],
    },
    no: {
      helperText: "Ótimo. Manter alguma previsibilidade nas refeições ajuda muito.",
      score: 1,
      topics: ["regularidade_refeicoes"],
    },
  }),
  yesNoQuestion({
    id: "adulto-feijao",
    ageGroup: "adulto",
    sectionId: "grupos-alimentares",
    title: "Você consome feijão ou outras leguminosas com regularidade?",
    yes: {
      helperText: "Boa prática! Isso favorece saciedade e qualidade da alimentação.",
      score: 1,
      topics: ["feijao_e_leguminosas"],
    },
    no: {
      helperText: "Vale buscar um jeito prático de incluir esse grupo mais vezes na semana.",
      score: -1,
      flags: ["baixo_consumo_leguminosas"],
      topics: ["feijao_e_leguminosas", "planejamento_alimentar"],
    },
  }),
  yesNoQuestion({
    id: "adulto-frutas",
    ageGroup: "adulto",
    sectionId: "grupos-alimentares",
    title: "Você consome frutas diariamente?",
    yes: {
      helperText: "Muito bem. Essa é uma prática protetora e prática no dia a dia.",
      score: 1,
      topics: ["frutas_e_verduras"],
    },
    no: {
      helperText: "Vale atenção: ter frutas mais visíveis e acessíveis pode ajudar bastante.",
      score: -1,
      flags: ["baixo_consumo_frutas_verduras"],
      topics: ["frutas_e_verduras", "planejamento_alimentar"],
    },
  }),
  yesNoQuestion({
    id: "adulto-verduras",
    ageGroup: "adulto",
    sectionId: "grupos-alimentares",
    title: "Você consome verduras e legumes diariamente?",
    yes: {
      helperText: "Boa prática! Isso aumenta variedade e qualidade das refeições.",
      score: 1,
      topics: ["frutas_e_verduras"],
    },
    no: {
      helperText: "Pequenos ajustes no preparo e nas compras podem facilitar esse consumo.",
      score: -1,
      flags: ["baixo_consumo_frutas_verduras"],
      topics: ["frutas_e_verduras", "planejamento_alimentar"],
    },
  }),
  singleChoiceQuestion({
    id: "adulto-ultraprocessados",
    ageGroup: "adulto",
    sectionId: "grupos-alimentares",
    title: "Com que frequência você consome alimentos ultraprocessados?",
    type: "frequency",
    options: [
      option({ value: "raramente", label: "Raramente", score: 1, topics: ["ultraprocessados"] }),
      option({ value: "1_2", label: "1 a 2 vezes por semana", score: 0, topics: ["ultraprocessados"] }),
      option({ value: "3_4", label: "3 a 4 vezes por semana", score: -1, flags: ["alto_consumo_ultraprocessados"], topics: ["ultraprocessados", "planejamento_alimentar"] }),
      option({ value: "frequente", label: "Quase todos os dias", score: -2, flags: ["alto_consumo_ultraprocessados"], topics: ["ultraprocessados", "planejamento_alimentar"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adulto-bebidas-acucaradas",
    ageGroup: "adulto",
    sectionId: "grupos-alimentares",
    title: "Com que frequência você ingere refrigerantes ou bebidas açucaradas?",
    type: "frequency",
    options: [
      option({ value: "raramente", label: "Raramente", score: 1, topics: ["bebidas_acucaradas"] }),
      option({ value: "1_2", label: "1 a 2 vezes por semana", score: 0, topics: ["bebidas_acucaradas"] }),
      option({ value: "3_4", label: "3 a 4 vezes por semana", score: -1, flags: ["alto_consumo_bebidas_acucaradas"], topics: ["bebidas_acucaradas", "hidratacao"] }),
      option({ value: "frequente", label: "Quase todos os dias", score: -2, flags: ["alto_consumo_bebidas_acucaradas"], topics: ["bebidas_acucaradas", "hidratacao"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adulto-agua",
    ageGroup: "adulto",
    sectionId: "hidratacao",
    title: "Você bebe água ao longo do dia?",
    options: [
      option({ value: "sim", label: "Sim, com boa frequência", score: 1, topics: ["hidratacao"] }),
      option({ value: "as_vezes", label: "Às vezes", score: 0, topics: ["hidratacao"] }),
      option({ value: "nao", label: "Não com a frequência que gostaria", score: -1, flags: ["baixa_hidratacao"], topics: ["hidratacao"] }),
    ],
  }),
  yesNoQuestion({
    id: "adulto-constipacao",
    ageGroup: "adulto",
    sectionId: "sinais-alerta",
    title: "Você percebe constipação intestinal com frequência?",
    yes: {
      helperText: "Vale atenção para água, fibras e frequência do desconforto.",
      score: -1,
      flags: ["constipacao"],
      topics: ["saude_digestiva", "hidratacao"],
    },
    no: {
      helperText: "Ótimo. Isso sugere um bom equilíbrio da rotina intestinal.",
      score: 1,
      topics: ["saude_digestiva"],
    },
  }),
  singleChoiceQuestion({
    id: "adulto-ganho-peso",
    ageGroup: "adulto",
    sectionId: "sinais-alerta",
    title: "Você percebeu ganho de peso recente?",
    options: [
      option({ value: "nao", label: "Não", score: 1, topics: ["acompanhamento_clinico"] }),
      option({ value: "leve", label: "Sim, mas leve", score: -1, flags: ["preocupacao_peso"], topics: ["acompanhamento_clinico"] }),
      option({ value: "marcante", label: "Sim, de forma marcante", score: -2, flags: ["preocupacao_peso"], topics: ["acompanhamento_clinico", "ultraprocessados"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adulto-barreira",
    ageGroup: "adulto",
    sectionId: "contexto-familiar",
    title: "Hoje, qual barreira mais pesa para manter uma alimentação saudável?",
    allowNotes: {
      label: "Se quiser, descreva um pouco melhor.",
      placeholder: "Ex.: trabalho, custo, tempo, organização...",
      maxLength: 180,
    },
    options: [
      option({ value: "tempo", label: "Falta de tempo", topics: ["planejamento_alimentar"] }),
      option({ value: "trabalho", label: "Rotina de trabalho", topics: ["planejamento_alimentar"] }),
      option({ value: "custo", label: "Dificuldade financeira", flags: ["vulnerabilidade_social"], topics: ["vulnerabilidade_social"] }),
      option({ value: "apoio", label: "Pouco apoio para organizar as refeições", flags: ["baixo_apoio_familiar"], topics: ["apoio_familiar"] }),
      option({ value: "nenhuma", label: "No momento consigo manter bem", score: 1, topics: ["planejamento_alimentar"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adulto-come-com-pressa",
    ageGroup: "adulto",
    sectionId: "habitos-diarios",
    title: "Com que frequência você come com pressa ou diante de telas?",
    options: [
      option({ value: "raramente", label: "Raramente", score: 1, topics: ["rotina_sem_telas"] }),
      option({ value: "as_vezes", label: "Às vezes", score: 0, topics: ["rotina_sem_telas"] }),
      option({ value: "frequente", label: "Com frequência", score: -1, flags: ["refeicoes_com_tela"], topics: ["rotina_sem_telas"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adulto-atividade-fisica",
    ageGroup: "adulto",
    sectionId: "habitos-diarios",
    title: "Como está sua rotina de atividade física?",
    options: [
      option({ value: "regular", label: "Regular", score: 1, topics: ["atividade_fisica"] }),
      option({ value: "alguma", label: "Faço alguma atividade", score: 0, topics: ["atividade_fisica"] }),
      option({ value: "quase_nunca", label: "Quase nunca", score: -1, flags: ["baixa_atividade_fisica"], topics: ["atividade_fisica"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "adulto-sono",
    ageGroup: "adulto",
    sectionId: "habitos-diarios",
    title: "Você sente que dorme adequadamente?",
    options: [
      option({ value: "sim", label: "Sim", score: 1, topics: ["sono"] }),
      option({ value: "parcial", label: "Parcialmente", score: 0, topics: ["sono"] }),
      option({ value: "nao", label: "Não", score: -1, flags: ["sono_irregular"], topics: ["sono"] }),
    ],
  }),
  multiChoiceQuestion({
    id: "adulto-condicoes-clinicas",
    ageGroup: "adulto",
    sectionId: "condicoes-clinicas",
    title: "Você possui alguma dessas condições clínicas?",
    description: "Você pode marcar mais de uma opção.",
    options: [
      option({ value: "hipertensao", label: "Hipertensão", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "diabetes", label: "Diabetes", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "colesterol", label: "Colesterol alto", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "nenhuma", label: "Nenhuma dessas", exclusive: true, score: 1, topics: ["acompanhamento_clinico"] }),
    ],
  }),
  yesNoQuestion({
    id: "adulto-acompanhamento",
    ageGroup: "adulto",
    sectionId: "condicoes-clinicas",
    title: "Quando necessário, você consegue manter acompanhamento com a equipe de saúde?",
    visibleWhen: [
      {
        questionId: "adulto-condicoes-clinicas",
        operator: "includes-any",
        value: ["hipertensao", "diabetes", "colesterol"],
      },
    ],
    yes: {
      helperText: "Ótimo. Isso ajuda a alinhar alimentação, medicação e rotina.",
      score: 1,
      topics: ["acompanhamento_clinico"],
    },
    no: {
      helperText: "Esse ponto merece atenção para apoiar melhor o cuidado contínuo.",
      score: -1,
      topics: ["acompanhamento_clinico"],
    },
  }),
];
