import { multiChoiceQuestion, option, singleChoiceQuestion, yesNoQuestion } from "../builders";
import { TriageQuestion } from "../../types";

export const fluxoCrianca: TriageQuestion[] = [
  singleChoiceQuestion({
    id: "crianca-responsavel-refeicoes",
    ageGroup: "crianca",
    sectionId: "identificacao",
    title: "Quem costuma acompanhar mais de perto a alimentação da criança?",
    description: "Isso ajuda a entender quem organiza as refeições no dia a dia.",
    options: [
      option({ value: "familia", label: "Família ou responsável", score: 1, topics: ["apoio_familiar"] }),
      option({ value: "escola", label: "Escola ou creche", score: 0, topics: ["alimentacao_escolar_rotina"] }),
      option({ value: "familia_ampliada", label: "Avós ou outra pessoa da família", score: 0, topics: ["apoio_familiar"] }),
      option({ value: "compartilhado", label: "É compartilhado entre várias pessoas", score: 0, topics: ["apoio_familiar"] }),
    ],
  }),
  yesNoQuestion({
    id: "crianca-cafe-da-manha",
    ageGroup: "crianca",
    sectionId: "rotina-alimentar",
    title: "A criança faz café da manhã na maioria dos dias?",
    yes: {
      helperText: "Muito bem! Essa refeição ajuda a começar o dia com mais energia.",
      score: 1,
      topics: ["cafe_da_manha"],
    },
    no: {
      helperText: "Vale atenção: organizar um café da manhã simples já pode ajudar bastante.",
      score: -1,
      flags: ["cafe_da_manha_irregular"],
      topics: ["cafe_da_manha", "planejamento_alimentar"],
    },
  }),
  singleChoiceQuestion({
    id: "crianca-refeicoes-dia",
    ageGroup: "crianca",
    sectionId: "rotina-alimentar",
    title: "Quantas refeições a criança costuma fazer por dia?",
    options: [
      option({ value: "2_ou_menos", label: "Até 2 refeições", score: -2, flags: ["baixa_frequencia_refeicoes"], topics: ["regularidade_refeicoes"] }),
      option({ value: "3", label: "3 refeições", score: 0, topics: ["regularidade_refeicoes"] }),
      option({ value: "4_5", label: "4 a 5 refeições", score: 1, topics: ["regularidade_refeicoes"] }),
      option({ value: "6_ou_mais", label: "6 ou mais", score: 0, topics: ["regularidade_refeicoes"] }),
    ],
  }),
  yesNoQuestion({
    id: "crianca-feijao-semana",
    ageGroup: "crianca",
    sectionId: "grupos-alimentares",
    title: "A criança costuma comer feijão durante a semana?",
    yes: {
      helperText: "Boa prática! O feijão ajuda no ferro, fibras e saciedade.",
      score: 1,
      topics: ["feijao_e_leguminosas"],
    },
    no: {
      helperText: "Vale buscar formas simples de incluir feijão ou outras leguminosas na rotina.",
      score: -1,
      flags: ["baixo_consumo_leguminosas"],
      topics: ["feijao_e_leguminosas", "planejamento_alimentar"],
    },
  }),
  yesNoQuestion({
    id: "crianca-frutas-diarias",
    ageGroup: "crianca",
    sectionId: "grupos-alimentares",
    title: "A criança consome frutas diariamente?",
    yes: {
      helperText: "Muito bem! Essa prática ajuda no intestino e na variedade alimentar.",
      score: 1,
      topics: ["frutas_e_verduras"],
    },
    no: {
      helperText: "Pequenos ajustes já podem ajudar a colocar fruta com mais frequência no dia a dia.",
      score: -1,
      flags: ["baixo_consumo_frutas_verduras"],
      topics: ["frutas_e_verduras", "planejamento_alimentar"],
    },
  }),
  multiChoiceQuestion({
    id: "crianca-barreiras-frutas",
    ageGroup: "crianca",
    sectionId: "grupos-alimentares",
    title: "O que mais dificulta oferecer frutas todos os dias?",
    description: "Você pode marcar mais de uma opção.",
    visibleWhen: [{ questionId: "crianca-frutas-diarias", operator: "equals", value: "nao" }],
    options: [
      option({ value: "recusa", label: "A criança recusa", topics: ["aceitacao_alimentar"] }),
      option({ value: "rotina", label: "A rotina é corrida", topics: ["planejamento_alimentar", "alimentacao_escolar_rotina"] }),
      option({ value: "custo", label: "O custo pesa", flags: ["vulnerabilidade_social"], topics: ["vulnerabilidade_social", "frutas_e_verduras"] }),
      option({ value: "preparo", label: "Falta tempo para preparar", topics: ["planejamento_alimentar"] }),
    ],
  }),
  yesNoQuestion({
    id: "crianca-verduras-diarias",
    ageGroup: "crianca",
    sectionId: "grupos-alimentares",
    title: "A criança consome verduras ou legumes todos os dias?",
    yes: {
      helperText: "Boa prática! Isso ajuda a ampliar a variedade do prato.",
      score: 1,
      topics: ["frutas_e_verduras"],
    },
    no: {
      helperText: "Vale atenção: variar o preparo pode facilitar a aceitação.",
      score: -1,
      flags: ["baixo_consumo_frutas_verduras"],
      topics: ["frutas_e_verduras", "aceitacao_alimentar"],
    },
  }),
  singleChoiceQuestion({
    id: "crianca-bebidas-adocadas",
    ageGroup: "crianca",
    sectionId: "grupos-alimentares",
    title: "Com que frequência a criança toma refrigerante, suco artificial ou bebida adoçada?",
    type: "frequency",
    options: [
      option({ value: "nunca", label: "Quase nunca", score: 1, topics: ["bebidas_acucaradas"] }),
      option({ value: "1_2_semana", label: "1 a 2 vezes por semana", score: 0, topics: ["bebidas_acucaradas"] }),
      option({ value: "3_4_semana", label: "3 a 4 vezes por semana", score: -1, flags: ["alto_consumo_bebidas_acucaradas"], topics: ["bebidas_acucaradas", "hidratacao"] }),
      option({ value: "5_ou_mais", label: "5 vezes ou mais", score: -2, flags: ["alto_consumo_bebidas_acucaradas"], topics: ["bebidas_acucaradas", "hidratacao"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "crianca-ultraprocessados",
    ageGroup: "crianca",
    sectionId: "grupos-alimentares",
    title: "Com que frequência a criança consome biscoito recheado, salgadinho ou doces?",
    type: "frequency",
    options: [
      option({ value: "raramente", label: "Raramente", score: 1, topics: ["ultraprocessados"] }),
      option({ value: "1_2_semana", label: "1 a 2 vezes por semana", score: 0, topics: ["ultraprocessados"] }),
      option({ value: "3_4_semana", label: "3 a 4 vezes por semana", score: -1, flags: ["alto_consumo_ultraprocessados"], topics: ["ultraprocessados"] }),
      option({ value: "diario", label: "Quase todos os dias", score: -2, flags: ["alto_consumo_ultraprocessados"], topics: ["ultraprocessados", "planejamento_alimentar"] }),
    ],
  }),
  yesNoQuestion({
    id: "crianca-agua-dia",
    ageGroup: "crianca",
    sectionId: "hidratacao",
    title: "A criança costuma beber água ao longo do dia?",
    yes: {
      helperText: "Muito bem! A água faz diferença para energia e funcionamento do intestino.",
      score: 1,
      topics: ["hidratacao"],
    },
    no: {
      helperText: "Vale combinar lembretes simples e deixar a água mais acessível.",
      score: -1,
      flags: ["baixa_hidratacao"],
      topics: ["hidratacao", "alimentacao_escolar_rotina"],
    },
  }),
  yesNoQuestion({
    id: "crianca-rotina-escola-hidratacao",
    ageGroup: "crianca",
    sectionId: "hidratacao",
    title: "A rotina de escola ou creche dificulta a hidratação?",
    description: "Pense em acesso à garrafinha, pausas e lembretes.",
    visibleWhen: [{ questionId: "crianca-agua-dia", operator: "equals", value: "nao" }],
    yes: {
      helperText: "Faz sentido. Nesse caso, vale pensar em estratégias bem práticas para fora de casa.",
      score: -1,
      topics: ["hidratacao", "alimentacao_escolar_rotina"],
    },
    no: {
      helperText: "Ótimo, então pequenos lembretes podem ser o principal apoio.",
      score: 0,
      topics: ["hidratacao"],
    },
  }),
  yesNoQuestion({
    id: "crianca-seletividade",
    ageGroup: "crianca",
    sectionId: "sinais-alerta",
    title: "Há dificuldade para a criança aceitar alimentos novos?",
    yes: {
      helperText: "Esse ponto pede acolhimento e repetição sem pressão.",
      score: -1,
      flags: ["seletividade_alimentar"],
      topics: ["aceitacao_alimentar", "apoio_familiar"],
    },
    no: {
      helperText: "Boa prática: a variedade tende a ficar mais fácil quando a rotina é tranquila.",
      score: 1,
      topics: ["aceitacao_alimentar"],
    },
  }),
  multiChoiceQuestion({
    id: "crianca-seletividade-foco",
    ageGroup: "crianca",
    sectionId: "sinais-alerta",
    title: "Quando a recusa aparece, em que situação ela costuma ser maior?",
    description: "Você pode marcar mais de uma opção.",
    visibleWhen: [{ questionId: "crianca-seletividade", operator: "equals", value: "sim" }],
    options: [
      option({ value: "verduras", label: "Verduras e legumes", topics: ["aceitacao_alimentar", "frutas_e_verduras"] }),
      option({ value: "feijao", label: "Feijão e preparações parecidas", topics: ["aceitacao_alimentar", "feijao_e_leguminosas"] }),
      option({ value: "texturas", label: "Texturas diferentes", topics: ["aceitacao_alimentar"] }),
      option({ value: "misturados", label: "Pratos com alimentos misturados", topics: ["aceitacao_alimentar"] }),
    ],
  }),
  yesNoQuestion({
    id: "crianca-perda-apetite",
    ageGroup: "crianca",
    sectionId: "sinais-alerta",
    title: "A criança apresenta perda de apetite frequente?",
    yes: {
      helperText: "Vale observar há quanto tempo isso acontece e conversar com a equipe de saúde se persistir.",
      score: -1,
      flags: ["perda_apetite"],
      topics: ["saude_digestiva", "acompanhamento_clinico"],
    },
    no: {
      helperText: "Ótimo. Manter horários e refeições com tranquilidade ajuda bastante.",
      score: 1,
      topics: ["regularidade_refeicoes"],
    },
  }),
  yesNoQuestion({
    id: "crianca-constipacao",
    ageGroup: "crianca",
    sectionId: "sinais-alerta",
    title: "Há queixa de prisão de ventre?",
    yes: {
      helperText: "Vale atenção para água, frutas, legumes e frequência do desconforto.",
      score: -1,
      flags: ["constipacao"],
      topics: ["saude_digestiva", "hidratacao"],
    },
    no: {
      helperText: "Muito bem. Essa rotina sugere bom cuidado com água e alimentos variados.",
      score: 1,
      topics: ["saude_digestiva"],
    },
  }),
  singleChoiceQuestion({
    id: "crianca-preocupacao-peso",
    ageGroup: "crianca",
    sectionId: "sinais-alerta",
    title: "Existe alguma preocupação atual com o peso da criança?",
    options: [
      option({ value: "nao", label: "Não há preocupação", score: 1, topics: ["acompanhamento_clinico"] }),
      option({ value: "baixo_peso", label: "Há preocupação com baixo peso", score: -1, flags: ["preocupacao_peso"], topics: ["acompanhamento_clinico"] }),
      option({ value: "ganho_excessivo", label: "Há preocupação com ganho excessivo", score: -1, flags: ["preocupacao_peso"], topics: ["acompanhamento_clinico", "ultraprocessados"] }),
    ],
  }),
  yesNoQuestion({
    id: "crianca-refeicoes-familia",
    ageGroup: "crianca",
    sectionId: "contexto-familiar",
    title: "A família costuma comer junto em alguns momentos da semana?",
    yes: {
      helperText: "Boa prática! Comer junto fortalece rotina, exemplo e vínculo.",
      score: 1,
      topics: ["apoio_familiar"],
    },
    no: {
      helperText: "Vale atenção: mesmo um ou dois momentos por semana já podem ajudar bastante.",
      score: -1,
      flags: ["baixo_apoio_familiar"],
      topics: ["apoio_familiar", "planejamento_alimentar"],
    },
  }),
  singleChoiceQuestion({
    id: "crianca-desafio-principal",
    ageGroup: "crianca",
    sectionId: "contexto-familiar",
    title: "Hoje, qual é o principal desafio para manter uma alimentação saudável?",
    allowNotes: {
      label: "Se quiser, conte um detalhe que ajude a entender melhor.",
      placeholder: "Ex.: horários corridos, recusa, custo, escola...",
      maxLength: 180,
    },
    options: [
      option({ value: "rotina", label: "Rotina corrida", topics: ["planejamento_alimentar"] }),
      option({ value: "recusa", label: "Recusa da criança", topics: ["aceitacao_alimentar"] }),
      option({ value: "custo", label: "Custo dos alimentos", flags: ["vulnerabilidade_social"], topics: ["vulnerabilidade_social"] }),
      option({ value: "escola", label: "Rotina de escola/creche", topics: ["alimentacao_escolar_rotina"] }),
      option({ value: "sem_desafio", label: "No momento está funcionando bem", score: 1, topics: ["apoio_familiar"] }),
    ],
  }),
  yesNoQuestion({
    id: "crianca-telas-refeicoes",
    ageGroup: "crianca",
    sectionId: "habitos-diarios",
    title: "A criança costuma comer assistindo TV, celular ou tablet?",
    yes: {
      helperText: "Vale atenção: reduzir telas nas refeições ajuda a perceber melhor a fome e a saciedade.",
      score: -1,
      flags: ["refeicoes_com_tela"],
      topics: ["rotina_sem_telas"],
    },
    no: {
      helperText: "Muito bem! Refeições com mais atenção ajudam a criança a comer com tranquilidade.",
      score: 1,
      topics: ["rotina_sem_telas"],
    },
  }),
  yesNoQuestion({
    id: "crianca-brincadeiras-ativas",
    ageGroup: "crianca",
    sectionId: "habitos-diarios",
    title: "A criança pratica brincadeiras ativas diariamente?",
    yes: {
      helperText: "Ótima prática! Movimento diário ajuda no desenvolvimento e no bem-estar.",
      score: 1,
      topics: ["atividade_fisica"],
    },
    no: {
      helperText: "Vale buscar oportunidades simples de movimento ao longo do dia.",
      score: -1,
      flags: ["baixa_atividade_fisica"],
      topics: ["atividade_fisica"],
    },
  }),
  singleChoiceQuestion({
    id: "crianca-sono-rotina",
    ageGroup: "crianca",
    sectionId: "habitos-diarios",
    title: "Como está a rotina de sono da criança?",
    options: [
      option({ value: "regular", label: "Regular na maior parte dos dias", score: 1, topics: ["sono"] }),
      option({ value: "as_vezes", label: "Oscila ao longo da semana", score: 0, topics: ["sono"] }),
      option({ value: "irregular", label: "Está bem irregular", score: -1, flags: ["sono_irregular"], topics: ["sono"] }),
    ],
  }),
  multiChoiceQuestion({
    id: "crianca-condicoes-clinicas",
    ageGroup: "crianca",
    sectionId: "condicoes-clinicas",
    title: "Existe alguma condição clínica já conhecida para essa criança?",
    description: "Você pode marcar mais de uma opção.",
    options: [
      option({ value: "obesidade", label: "Obesidade", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "hipertensao", label: "Hipertensão arterial", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "diabetes", label: "Diabetes", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "nenhuma", label: "Nenhuma dessas", exclusive: true, score: 1, topics: ["acompanhamento_clinico"] }),
    ],
  }),
  yesNoQuestion({
    id: "crianca-acompanhamento-profissional",
    ageGroup: "crianca",
    sectionId: "condicoes-clinicas",
    title: "Quando necessário, a criança tem acompanhamento com a equipe de saúde?",
    visibleWhen: [
      {
        questionId: "crianca-condicoes-clinicas",
        operator: "includes-any",
        value: ["obesidade", "hipertensao", "diabetes"],
      },
    ],
    yes: {
      helperText: "Ótimo. O acompanhamento ajuda a adaptar melhor as orientações ao contexto real da família.",
      score: 1,
      topics: ["acompanhamento_clinico"],
    },
    no: {
      helperText: "Esse ponto merece mais atenção para garantir cuidado compartilhado com a equipe de saúde.",
      score: -1,
      topics: ["acompanhamento_clinico"],
    },
  }),
];
