import { multiChoiceQuestion, option, singleChoiceQuestion, yesNoQuestion } from "../builders";
import { TriageQuestion } from "../../types";

export const fluxoGestante: TriageQuestion[] = [
  singleChoiceQuestion({
    id: "gestante-trimestre",
    ageGroup: "gestante",
    sectionId: "identificacao",
    title: "Em que período da gestação você está?",
    options: [
      option({ value: "primeiro", label: "Primeiro trimestre", score: 0, topics: ["alimentacao_gestacao", "pre_natal"] }),
      option({ value: "segundo", label: "Segundo trimestre", score: 0, topics: ["alimentacao_gestacao", "pre_natal"] }),
      option({ value: "terceiro", label: "Terceiro trimestre", score: 0, topics: ["alimentacao_gestacao", "pre_natal"] }),
      option({ value: "prefiro_nao", label: "Prefiro não informar", score: 0, topics: ["alimentacao_gestacao"] }),
    ],
  }),
  yesNoQuestion({
    id: "gestante-pre-natal",
    ageGroup: "gestante",
    sectionId: "rotina-alimentar",
    title: "Você está realizando pré-natal?",
    yes: {
      helperText: "Muito bem. Esse acompanhamento ajuda bastante ao longo da gestação.",
      score: 1,
      topics: ["pre_natal"],
    },
    no: {
      helperText: "Esse ponto merece acompanhamento prioritário com a equipe de saúde.",
      score: -3,
      flags: ["sem_pre_natal"],
      topics: ["pre_natal", "acompanhamento_clinico"],
    },
  }),
  singleChoiceQuestion({
    id: "gestante-refeicoes-dia",
    ageGroup: "gestante",
    sectionId: "rotina-alimentar",
    title: "Quantas refeições você costuma fazer por dia?",
    options: [
      option({ value: "2_ou_menos", label: "Até 2 refeições", score: -2, flags: ["baixa_frequencia_refeicoes"], topics: ["regularidade_refeicoes", "alimentacao_gestacao"] }),
      option({ value: "3", label: "3 refeições", score: 0, topics: ["regularidade_refeicoes", "alimentacao_gestacao"] }),
      option({ value: "4_5", label: "4 a 5 refeições", score: 1, topics: ["regularidade_refeicoes", "alimentacao_gestacao"] }),
      option({ value: "6_ou_mais", label: "6 ou mais", score: 0, topics: ["regularidade_refeicoes", "alimentacao_gestacao"] }),
    ],
  }),
  yesNoQuestion({
    id: "gestante-enjoo",
    ageGroup: "gestante",
    sectionId: "rotina-alimentar",
    title: "Você tem dificuldade para se alimentar por enjoo?",
    yes: {
      helperText: "Tudo bem. Vale pensar em estratégias mais confortáveis ao longo do dia.",
      score: -1,
      topics: ["alimentacao_gestacao", "pre_natal"],
    },
    no: {
      helperText: "Ótimo. Isso favorece uma rotina alimentar mais estável.",
      score: 1,
      topics: ["alimentacao_gestacao"],
    },
  }),
  singleChoiceQuestion({
    id: "gestante-enjoo-periodo",
    ageGroup: "gestante",
    sectionId: "rotina-alimentar",
    title: "Em qual período do dia o enjoo costuma ser pior?",
    visibleWhen: [{ questionId: "gestante-enjoo", operator: "equals", value: "sim" }],
    options: [
      option({ value: "manha", label: "Manhã", topics: ["alimentacao_gestacao"] }),
      option({ value: "tarde", label: "Tarde", topics: ["alimentacao_gestacao"] }),
      option({ value: "noite", label: "Noite", topics: ["alimentacao_gestacao"] }),
      option({ value: "dia_todo", label: "Ao longo de todo o dia", topics: ["alimentacao_gestacao", "pre_natal"] }),
    ],
  }),
  yesNoQuestion({
    id: "gestante-longos-periodos",
    ageGroup: "gestante",
    sectionId: "rotina-alimentar",
    title: "Você costuma ficar longos períodos sem comer?",
    yes: {
      helperText: "Vale atenção: pequenas refeições mais frequentes podem ajudar bastante.",
      score: -1,
      flags: ["longos_periodos_sem_comer"],
      topics: ["regularidade_refeicoes", "alimentacao_gestacao"],
    },
    no: {
      helperText: "Boa prática. Isso ajuda a organizar melhor o dia e o bem-estar.",
      score: 1,
      topics: ["regularidade_refeicoes", "alimentacao_gestacao"],
    },
  }),
  yesNoQuestion({
    id: "gestante-fontes-ferro",
    ageGroup: "gestante",
    sectionId: "grupos-alimentares",
    title: "Você costuma consumir feijão, carnes, ovos ou outras fontes de ferro?",
    yes: {
      helperText: "Muito bem. Esses alimentos ajudam bastante no cuidado nutricional da gestação.",
      score: 1,
      topics: ["feijao_e_leguminosas", "alimentacao_gestacao"],
    },
    no: {
      helperText: "Vale combinar alternativas com a equipe do pré-natal e com o que cabe na sua rotina.",
      score: -1,
      flags: ["baixo_consumo_leguminosas"],
      topics: ["feijao_e_leguminosas", "alimentacao_gestacao"],
    },
  }),
  yesNoQuestion({
    id: "gestante-frutas-verduras",
    ageGroup: "gestante",
    sectionId: "grupos-alimentares",
    title: "Você consome frutas, verduras e legumes diariamente?",
    yes: {
      helperText: "Ótima prática. Isso ajuda na variedade e no bem-estar durante a gestação.",
      score: 1,
      topics: ["frutas_e_verduras", "alimentacao_gestacao"],
    },
    no: {
      helperText: "Vale buscar combinações mais simples e possíveis para aumentar essa presença no dia a dia.",
      score: -1,
      flags: ["baixo_consumo_frutas_verduras"],
      topics: ["frutas_e_verduras", "alimentacao_gestacao", "planejamento_alimentar"],
    },
  }),
  singleChoiceQuestion({
    id: "gestante-ultraprocessados",
    ageGroup: "gestante",
    sectionId: "grupos-alimentares",
    title: "Com que frequência você consome muitos ultraprocessados?",
    type: "frequency",
    options: [
      option({ value: "raramente", label: "Raramente", score: 1, topics: ["ultraprocessados", "alimentacao_gestacao"] }),
      option({ value: "1_2", label: "1 a 2 vezes por semana", score: 0, topics: ["ultraprocessados", "alimentacao_gestacao"] }),
      option({ value: "3_4", label: "3 a 4 vezes por semana", score: -1, flags: ["alto_consumo_ultraprocessados"], topics: ["ultraprocessados", "planejamento_alimentar"] }),
      option({ value: "frequente", label: "Quase todos os dias", score: -2, flags: ["alto_consumo_ultraprocessados"], topics: ["ultraprocessados", "planejamento_alimentar"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "gestante-agua",
    ageGroup: "gestante",
    sectionId: "hidratacao",
    title: "Você bebe água com frequência ao longo do dia?",
    options: [
      option({ value: "sim", label: "Sim", score: 1, topics: ["hidratacao", "alimentacao_gestacao"] }),
      option({ value: "as_vezes", label: "Às vezes", score: 0, topics: ["hidratacao"] }),
      option({ value: "nao", label: "Não", score: -1, flags: ["baixa_hidratacao"], topics: ["hidratacao", "saude_digestiva"] }),
    ],
  }),
  yesNoQuestion({
    id: "gestante-constipacao",
    ageGroup: "gestante",
    sectionId: "sinais-alerta",
    title: "Você percebe prisão de ventre?",
    yes: {
      helperText: "Isso é comum, mas vale ajustar água, fibras e conversar no pré-natal se estiver incomodando.",
      score: -1,
      flags: ["constipacao"],
      topics: ["saude_digestiva", "hidratacao", "alimentacao_gestacao"],
    },
    no: {
      helperText: "Ótimo. Manter água e variedade alimentar ajuda bastante nessa rotina.",
      score: 1,
      topics: ["saude_digestiva"],
    },
  }),
  singleChoiceQuestion({
    id: "gestante-constipacao-padrao",
    ageGroup: "gestante",
    sectionId: "sinais-alerta",
    title: "Quando isso acontece, o que parece pesar mais?",
    visibleWhen: [{ questionId: "gestante-constipacao", operator: "equals", value: "sim" }],
    options: [
      option({ value: "agua_fibras", label: "Pouca água e poucas fibras", topics: ["hidratacao", "saude_digestiva"] }),
      option({ value: "mais_agua", label: "Preciso melhorar mais a água", topics: ["hidratacao"] }),
      option({ value: "mais_fibras", label: "Preciso melhorar mais as fibras", topics: ["frutas_e_verduras", "saude_digestiva"] }),
      option({ value: "nao_sei", label: "Ainda não sei identificar", topics: ["saude_digestiva", "pre_natal"] }),
    ],
  }),
  yesNoQuestion({
    id: "gestante-suplementos",
    ageGroup: "gestante",
    sectionId: "sinais-alerta",
    title: "Você faz uso de suplementos prescritos?",
    yes: {
      helperText: "Ótimo. Seguir a orientação ajuda no cuidado nutricional da gestação.",
      score: 1,
      topics: ["suplementacao", "pre_natal"],
    },
    no: {
      helperText: "Vale conversar no pré-natal sobre suplementação, quando ela for indicada.",
      score: 0,
      topics: ["suplementacao", "pre_natal"],
    },
  }),
  singleChoiceQuestion({
    id: "gestante-apoio-preparo",
    ageGroup: "gestante",
    sectionId: "contexto-familiar",
    title: "Você tem acesso e apoio para preparar suas refeições?",
    options: [
      option({ value: "bom_apoio", label: "Sim, com bom apoio", score: 1, topics: ["apoio_familiar"] }),
      option({ value: "algum_apoio", label: "Tenho algum apoio", score: 0, topics: ["apoio_familiar"] }),
      option({ value: "pouco_apoio", label: "Tenho pouco apoio", score: -1, flags: ["baixo_apoio_familiar"], topics: ["apoio_familiar", "vulnerabilidade_social"] }),
    ],
  }),
  yesNoQuestion({
    id: "gestante-orientacao-profissional",
    ageGroup: "gestante",
    sectionId: "contexto-familiar",
    title: "Você recebeu orientação alimentar profissional durante a gestação?",
    yes: {
      helperText: "Ótimo. Isso ajuda a adaptar melhor as orientações à sua rotina.",
      score: 1,
      topics: ["pre_natal", "acompanhamento_clinico"],
    },
    no: {
      helperText: "Vale pedir esse apoio no pré-natal, principalmente se houver enjoo ou dificuldade para comer.",
      score: 0,
      topics: ["pre_natal", "acompanhamento_clinico"],
    },
  }),
  singleChoiceQuestion({
    id: "gestante-desafio",
    ageGroup: "gestante",
    sectionId: "contexto-familiar",
    title: "Qual tem sido o principal desafio para cuidar da alimentação nessa fase?",
    allowNotes: {
      label: "Se quiser, escreva um pouco mais.",
      placeholder: "Ex.: enjoo, rotina, custo, preparo, apoio...",
      maxLength: 180,
    },
    options: [
      option({ value: "enjoo", label: "Enjoos", topics: ["alimentacao_gestacao", "pre_natal"] }),
      option({ value: "tempo", label: "Falta de tempo", topics: ["planejamento_alimentar"] }),
      option({ value: "custo", label: "Custo dos alimentos", flags: ["vulnerabilidade_social"], topics: ["vulnerabilidade_social"] }),
      option({ value: "apoio", label: "Pouco apoio em casa", flags: ["baixo_apoio_familiar"], topics: ["apoio_familiar"] }),
      option({ value: "nenhum", label: "No momento está funcionando bem", score: 1, topics: ["apoio_familiar"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "gestante-movimento",
    ageGroup: "gestante",
    sectionId: "habitos-diarios",
    title: "Você consegue incluir algum movimento corporal orientado ou confortável na rotina?",
    options: [
      option({ value: "regular", label: "Sim, com regularidade", score: 1, topics: ["atividade_fisica"] }),
      option({ value: "as_vezes", label: "Às vezes", score: 0, topics: ["atividade_fisica"] }),
      option({ value: "nao", label: "Não tenho conseguido", score: -1, flags: ["baixa_atividade_fisica"], topics: ["atividade_fisica", "pre_natal"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "gestante-sono",
    ageGroup: "gestante",
    sectionId: "habitos-diarios",
    title: "Como está o seu descanso e sono?",
    options: [
      option({ value: "bom", label: "Bom na maior parte dos dias", score: 1, topics: ["sono"] }),
      option({ value: "irregular", label: "Oscila bastante", score: 0, topics: ["sono"] }),
      option({ value: "ruim", label: "Está ruim", score: -1, flags: ["sono_irregular"], topics: ["sono", "pre_natal"] }),
    ],
  }),
  multiChoiceQuestion({
    id: "gestante-condicoes",
    ageGroup: "gestante",
    sectionId: "condicoes-clinicas",
    title: "Existe alguma condição clínica relevante acompanhada nesta gestação?",
    description: "Você pode marcar mais de uma opção.",
    options: [
      option({ value: "pressao_alta", label: "Pressão alta", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico", "pre_natal"] }),
      option({ value: "diabetes_gestacional", label: "Diabetes gestacional", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico", "pre_natal"] }),
      option({ value: "anemia", label: "Anemia", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico", "alimentacao_gestacao"] }),
      option({ value: "nenhuma", label: "Nenhuma dessas", exclusive: true, score: 1, topics: ["acompanhamento_clinico"] }),
    ],
  }),
];
