import { multiChoiceQuestion, option, singleChoiceQuestion, yesNoQuestion } from "../builders";
import { TriageQuestion } from "../../types";

export const fluxoIdoso: TriageQuestion[] = [
  singleChoiceQuestion({
    id: "idoso-preparo-refeicoes",
    ageGroup: "idoso",
    sectionId: "identificacao",
    title: "Quem costuma preparar a maior parte das refeições?",
    options: [
      option({ value: "eu", label: "Eu mesmo(a)", score: 1, topics: ["autonomia_alimentar"] }),
      option({ value: "familia", label: "Família ou cuidador", score: 0, topics: ["apoio_familiar"] }),
      option({ value: "compartilhado", label: "É alternado", score: 0, topics: ["apoio_familiar"] }),
      option({ value: "depende", label: "Depende do dia", score: 0, topics: ["apoio_familiar"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "idoso-refeicoes-dia",
    ageGroup: "idoso",
    sectionId: "rotina-alimentar",
    title: "Quantas refeições você costuma fazer por dia?",
    options: [
      option({ value: "2_ou_menos", label: "Até 2 refeições", score: -2, flags: ["baixa_frequencia_refeicoes"], topics: ["regularidade_refeicoes"] }),
      option({ value: "3", label: "3 refeições", score: 0, topics: ["regularidade_refeicoes"] }),
      option({ value: "4_5", label: "4 a 5 refeições", score: 1, topics: ["regularidade_refeicoes"] }),
      option({ value: "6_ou_mais", label: "6 ou mais", score: 0, topics: ["regularidade_refeicoes"] }),
    ],
  }),
  yesNoQuestion({
    id: "idoso-apetite",
    ageGroup: "idoso",
    sectionId: "rotina-alimentar",
    title: "Você tem perdido o apetite?",
    yes: {
      helperText: "Vale observar a frequência e levar esse ponto para avaliação se estiver persistente.",
      score: -1,
      flags: ["perda_apetite"],
      topics: ["saude_digestiva", "acompanhamento_clinico"],
    },
    no: {
      helperText: "Ótimo. Isso sugere uma rotina alimentar mais estável.",
      score: 1,
      topics: ["regularidade_refeicoes"],
    },
  }),
  yesNoQuestion({
    id: "idoso-longos-periodos",
    ageGroup: "idoso",
    sectionId: "rotina-alimentar",
    title: "Você fica muitas horas sem comer?",
    yes: {
      helperText: "Vale atenção: reduzir intervalos longos pode ajudar no conforto e na disposição.",
      score: -1,
      flags: ["longos_periodos_sem_comer"],
      topics: ["regularidade_refeicoes", "planejamento_alimentar"],
    },
    no: {
      helperText: "Boa prática. Refeições mais regulares ajudam bastante no dia a dia.",
      score: 1,
      topics: ["regularidade_refeicoes"],
    },
  }),
  yesNoQuestion({
    id: "idoso-feijao",
    ageGroup: "idoso",
    sectionId: "grupos-alimentares",
    title: "Você consome feijão ou outras leguminosas com frequência?",
    yes: {
      helperText: "Boa prática! Esse grupo ajuda bastante na qualidade da alimentação.",
      score: 1,
      topics: ["feijao_e_leguminosas"],
    },
    no: {
      helperText: "Vale pensar em preparações mais macias e práticas quando possível.",
      score: -1,
      flags: ["baixo_consumo_leguminosas"],
      topics: ["feijao_e_leguminosas", "planejamento_alimentar"],
    },
  }),
  yesNoQuestion({
    id: "idoso-frutas-verduras",
    ageGroup: "idoso",
    sectionId: "grupos-alimentares",
    title: "Você consome frutas, verduras e legumes com frequência?",
    yes: {
      helperText: "Muito bem. Isso ajuda no intestino e na variedade alimentar.",
      score: 1,
      topics: ["frutas_e_verduras"],
    },
    no: {
      helperText: "Vale atenção: preparações mais macias e já prontas podem facilitar esse consumo.",
      score: -1,
      flags: ["baixo_consumo_frutas_verduras"],
      topics: ["frutas_e_verduras", "planejamento_alimentar", "mastigacao_e_degluticao"],
    },
  }),
  yesNoQuestion({
    id: "idoso-agua",
    ageGroup: "idoso",
    sectionId: "hidratacao",
    title: "Você bebe água regularmente ao longo do dia?",
    yes: {
      helperText: "Boa prática. A hidratação ajuda muito no bem-estar e no intestino.",
      score: 1,
      topics: ["hidratacao"],
    },
    no: {
      helperText: "Vale criar lembretes visíveis e combinar horários ao longo do dia.",
      score: -1,
      flags: ["baixa_hidratacao"],
      topics: ["hidratacao", "saude_digestiva"],
    },
  }),
  yesNoQuestion({
    id: "idoso-dificuldade-mastigar",
    ageGroup: "idoso",
    sectionId: "sinais-alerta",
    title: "Você tem dificuldade para mastigar?",
    yes: {
      helperText: "Esse ponto merece atenção, pois pode dificultar a alimentação e reduzir o apetite.",
      score: -2,
      flags: ["dificuldade_mastigar"],
      topics: ["mastigacao_e_degluticao", "acompanhamento_clinico"],
    },
    no: {
      helperText: "Ótimo. Isso ajuda a manter mais variedade nas refeições.",
      score: 1,
      topics: ["mastigacao_e_degluticao"],
    },
  }),
  yesNoQuestion({
    id: "idoso-dificuldade-engolir",
    ageGroup: "idoso",
    sectionId: "sinais-alerta",
    title: "Você tem dificuldade para engolir?",
    yes: {
      helperText: "Esse ponto merece acompanhamento prioritário com a equipe de saúde.",
      score: -3,
      flags: ["dificuldade_engolir"],
      topics: ["mastigacao_e_degluticao", "acompanhamento_clinico"],
    },
    no: {
      helperText: "Muito bem. Isso é um bom sinal para manter segurança na alimentação.",
      score: 1,
      topics: ["mastigacao_e_degluticao"],
    },
  }),
  yesNoQuestion({
    id: "idoso-perda-peso",
    ageGroup: "idoso",
    sectionId: "sinais-alerta",
    title: "Você perdeu peso sem querer recentemente?",
    yes: {
      helperText: "Esse ponto merece atenção prioritária, especialmente se vier junto de menos apetite ou dificuldade para comer.",
      score: -3,
      flags: ["perda_peso_involuntaria"],
      topics: ["acompanhamento_clinico", "mastigacao_e_degluticao"],
    },
    no: {
      helperText: "Ótimo. Manter acompanhamento do peso ajuda a observar mudanças com tempo.",
      score: 1,
      topics: ["acompanhamento_clinico"],
    },
  }),
  yesNoQuestion({
    id: "idoso-constipacao",
    ageGroup: "idoso",
    sectionId: "sinais-alerta",
    title: "Você percebe prisão de ventre com frequência?",
    yes: {
      helperText: "Vale atenção para água, fibras e rotina intestinal.",
      score: -1,
      flags: ["constipacao"],
      topics: ["saude_digestiva", "hidratacao"],
    },
    no: {
      helperText: "Ótimo. Isso sugere um equilíbrio melhor da rotina intestinal.",
      score: 1,
      topics: ["saude_digestiva"],
    },
  }),
  yesNoQuestion({
    id: "idoso-mora-sozinho",
    ageGroup: "idoso",
    sectionId: "contexto-familiar",
    title: "Você mora sozinho(a)?",
    yes: {
      helperText: "Tudo bem. Vale apenas observar se isso interfere nas compras, preparo ou horários.",
      score: -1,
      flags: ["baixo_apoio_familiar"],
      topics: ["apoio_familiar", "vulnerabilidade_social"],
    },
    no: {
      helperText: "Ter companhia pode ajudar a manter rotina e apoio no cuidado alimentar.",
      score: 1,
      topics: ["apoio_familiar"],
    },
  }),
  yesNoQuestion({
    id: "idoso-dificuldade-cozinhar",
    ageGroup: "idoso",
    sectionId: "contexto-familiar",
    title: "Você tem dificuldade para cozinhar ou comprar alimentos?",
    yes: {
      helperText: "Esse ponto merece atenção, porque pode afetar a regularidade das refeições.",
      score: -2,
      flags: ["vulnerabilidade_social"],
      topics: ["vulnerabilidade_social", "planejamento_alimentar", "apoio_familiar"],
    },
    no: {
      helperText: "Ótimo. Isso ajuda bastante a manter autonomia e rotina alimentar.",
      score: 1,
      topics: ["autonomia_alimentar"],
    },
  }),
  singleChoiceQuestion({
    id: "idoso-ajuda-familia",
    ageGroup: "idoso",
    sectionId: "contexto-familiar",
    title: "Você tem ajuda da família ou cuidador na alimentação quando precisa?",
    options: [
      option({ value: "sempre", label: "Sim, sempre que preciso", score: 1, topics: ["apoio_familiar"] }),
      option({ value: "as_vezes", label: "Às vezes", score: 0, topics: ["apoio_familiar"] }),
      option({ value: "raramente", label: "Raramente", score: -1, flags: ["baixo_apoio_familiar"], topics: ["apoio_familiar", "vulnerabilidade_social"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "idoso-movimento",
    ageGroup: "idoso",
    sectionId: "habitos-diarios",
    title: "Você consegue incluir algum movimento ou caminhada no dia a dia?",
    options: [
      option({ value: "sim", label: "Sim", score: 1, topics: ["atividade_fisica"] }),
      option({ value: "as_vezes", label: "Às vezes", score: 0, topics: ["atividade_fisica"] }),
      option({ value: "nao", label: "Não", score: -1, flags: ["baixa_atividade_fisica"], topics: ["atividade_fisica"] }),
    ],
  }),
  singleChoiceQuestion({
    id: "idoso-sono",
    ageGroup: "idoso",
    sectionId: "habitos-diarios",
    title: "Como está a qualidade do seu sono?",
    options: [
      option({ value: "boa", label: "Boa", score: 1, topics: ["sono"] }),
      option({ value: "irregular", label: "Irregular", score: 0, topics: ["sono"] }),
      option({ value: "ruim", label: "Ruim", score: -1, flags: ["sono_irregular"], topics: ["sono"] }),
    ],
  }),
  multiChoiceQuestion({
    id: "idoso-condicoes",
    ageGroup: "idoso",
    sectionId: "condicoes-clinicas",
    title: "Você possui alguma dessas condições clínicas?",
    description: "Você pode marcar mais de uma opção.",
    options: [
      option({ value: "hipertensao", label: "Hipertensão", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "diabetes", label: "Diabetes", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "cardiaca", label: "Doença cardíaca", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "outra", label: "Outra condição", flags: ["condicao_clinica_relevante"], topics: ["acompanhamento_clinico"] }),
      option({ value: "nenhuma", label: "Nenhuma dessas", exclusive: true, score: 1, topics: ["acompanhamento_clinico"] }),
    ],
  }),
  yesNoQuestion({
    id: "idoso-medicamentos",
    ageGroup: "idoso",
    sectionId: "condicoes-clinicas",
    title: "Você usa muitos medicamentos ao longo do dia?",
    yes: {
      helperText: "Vale atenção para manter acompanhamento e tirar dúvidas sobre horários e alimentação.",
      score: -1,
      flags: ["condicao_clinica_relevante"],
      topics: ["acompanhamento_clinico"],
    },
    no: {
      helperText: "Ótimo. Ainda assim, manter revisão periódica com a equipe segue sendo importante.",
      score: 0,
      topics: ["acompanhamento_clinico"],
    },
  }),
];
